import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import type { ChoiceResult } from '../types'
const KEY='love-language-save-v1'; const clamp=(v:number)=>Math.max(0,Math.min(100,v)); const today=()=>new Date().toLocaleDateString('sv-SE')
interface Save {version:1;name:string;onboarded:boolean;affection:number;trust:number;xp:number;studyDays:number;lastStudyDate:string;completed:number[];answers:Record<number,ChoiceResult>;reviews:string[];showTranslation:boolean}
const defaults:Save={version:1,name:'Haru',onboarded:false,affection:18,trust:12,xp:0,studyDays:0,lastStudyDate:'',completed:[],answers:{},reviews:[],showTranslation:true}
function load():Save{try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v?.version===1?{...defaults,...v,affection:clamp(v.affection),trust:clamp(v.trust)}:defaults}catch{return defaults}}
export const useAppStore=defineStore('app',()=>{const s=ref<Save>(load()); const relationship=computed(()=>s.value.affection>=75?'特別な存在':s.value.affection>=45?'気になる存在':s.value.affection>=25?'友達':'知り合い'); const currentChapter=computed(()=>Math.min(3,Math.max(1,s.value.completed.length+1))); const learnedCount=computed(()=>s.value.completed.reduce((n,id)=>n+[5,4,4][id-1],0));
 function persist(){localStorage.setItem(KEY,JSON.stringify(s.value))} function setName(name:string){s.value.name=name.trim();persist()} function finishOnboarding(){s.value.onboarded=true;persist()} function toggleTranslation(){s.value.showTranslation=!s.value.showTranslation;persist()} function complete(result:ChoiceResult){if(!s.value.completed.includes(result.chapterId)){s.value.affection=clamp(s.value.affection+result.choice.affectionChange);s.value.trust=clamp(s.value.trust+result.choice.trustChange);s.value.xp+=result.choice.englishXp;s.value.completed.push(result.chapterId);if(s.value.lastStudyDate!==today()){s.value.studyDays++;s.value.lastStudyDate=today()}}s.value.answers[result.chapterId]=result;persist()} function toggleReview(id:string){s.value.reviews=s.value.reviews.includes(id)?s.value.reviews.filter(x=>x!==id):[...s.value.reviews,id];persist()} function reset(){s.value={...defaults,answers:{},completed:[],reviews:[]};persist()}
 return{s,relationship,currentChapter,learnedCount,setName,finishOnboarding,toggleTranslation,complete,toggleReview,reset}})
